# Generated by Django 6.0.6 on 2026-07-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyvideo'),
        ('viewings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={},
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='preferred_date',
            new_name='requested_date',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='preferred_time',
            new_name='requested_time',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='message',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='viewing',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='customer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='viewing',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=300, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='viewing',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_reservations', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed')], default='pending_payment', max_length=30),
        ),
    ]
