# Generated by Django 6.0.6 on 2026-07-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
        ('properties', '0003_alter_property_partner'),
        ('viewings', '0003_viewingbooking_viewingbookingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='viewing',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_viewings', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='viewing',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='confirmed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='partner_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='partner_response_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='viewing',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_reservations', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('paid_pending_partner', 'Paid - awaiting partner'), ('reschedule_proposed', 'Partner proposed another time'), ('confirmed', 'Confirmed'), ('partner_en_route', 'Partner en route'), ('partner_arrived', 'Partner arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending_payment', max_length=30),
        ),
    ]
