# Generated by Django 6.0.6 on 2026-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0004_alter_viewing_options_viewing_assigned_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='partner_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='partner_departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='viewing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewingbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid_pending_partner', 'Paid — Awaiting Partner'), ('confirmed', 'Confirmed'), ('partner_en_route', 'Partner En Route'), ('partner_arrived', 'Partner Arrived'), ('viewing_in_progress', 'Viewing In Progress'), ('completed', 'Completed'), ('reschedule_proposed', 'Reschedule Proposed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=40),
        ),
    ]
