# Generated by Django 6.0.6 on 2026-07-18 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
        ('properties', '0003_alter_property_partner'),
        ('viewings', '0005_viewing_completion_notes_viewing_partner_arrived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_received', 'Payment received'), ('partner_confirmed', 'Partner confirmed'), ('reschedule_proposed', 'Reschedule proposed'), ('partner_en_route', 'Partner en route'), ('partner_arrived', 'Partner arrived'), ('viewing_started', 'Viewing started'), ('viewing_completed', 'Viewing completed'), ('customer_no_show', 'Customer did not attend'), ('partner_no_show', 'Partner did not attend'), ('viewing_cancelled', 'Viewing cancelled'), ('refund_issued', 'Refund issued'), ('dispute_opened', 'Dispute opened')], db_index=True, max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='viewingbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='completion_notes',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='partner_arrived_at',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='partner_departed_at',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='viewing_started_at',
        ),
        migrations.AlterField(
            model_name='viewing',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('paid_pending_partner', 'Paid - awaiting partner'), ('reschedule_proposed', 'Partner proposed another time'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='viewingbooking',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewingbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid_pending_partner', 'Paid - Awaiting Partner'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('reschedule_proposed', 'Reschedule Proposed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=40),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['customer', 'status', '-created_at'], name='viewing_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['assigned_partner', 'status', 'requested_date'], name='viewing_partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['property', 'requested_date', 'requested_time'], name='viewing_property_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingbooking',
            index=models.Index(fields=['customer', 'status', '-created_at'], name='vbooking_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingbooking',
            index=models.Index(fields=['assigned_partner', 'status', 'viewing_date'], name='vbooking_partner_status_idx'),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_viewing_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewingevent',
            name='viewing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='viewings.viewing'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['viewing', '-created_at'], name='viewevent_viewing_time_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingevent',
            index=models.Index(fields=['event_type', '-created_at'], name='viewevent_type_time_idx'),
        ),
    ]
