# Generated by Django 6.0.6 on 2026-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0006_viewingevent_alter_viewingbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('paid_pending_partner', 'Paid - awaiting partner'), ('reschedule_proposed', 'Partner proposed another time'), ('confirmed', 'Confirmed'), ('declined', 'Declined by partner'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=30),
        ),
    ]
