# Generated by Django 6.0.6 on 2026-07-25 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0007_alter_viewing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), editable=False, max_digits=10),
        ),
    ]
