# Generated by Django 6.0.6 on 2026-08-01 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0008_alter_viewing_fee_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('property_accuracy', models.CharField(choices=[('yes', 'Yes'), ('partially', 'Partially'), ('no', 'No')], max_length=20)),
                ('partner_rating', models.PositiveSmallIntegerField()),
                ('property_rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_feedback', to=settings.AUTH_USER_MODEL)),
                ('viewing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='viewings.viewing')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
