# Generated by Django 6.0.6 on 2026-08-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertypartner'),
        ('viewings', '0009_viewingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='source_participation',
            field=models.ForeignKey(blank=True, help_text='The property participation through which this viewing was assigned.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_viewings', to='properties.propertypartner'),
        ),
    ]
