# Generated by Django 6.0.6 on 2026-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0010_viewing_source_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='fee_resolution_choice',
            field=models.CharField(blank=True, choices=[('credit', 'Transferable viewing credit'), ('refund', 'Full refund')], default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='viewing',
            name='fee_resolution_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='reschedule_decline_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('paid_pending_partner', 'Paid - awaiting partner'), ('reschedule_proposed', 'Partner proposed another time'), ('scheduling_failed', 'Viewing time could not be agreed'), ('confirmed', 'Confirmed'), ('declined', 'Declined by partner'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='viewingevent',
            name='event_type',
            field=models.CharField(choices=[('payment_received', 'Payment received'), ('partner_confirmed', 'Partner confirmed'), ('reschedule_proposed', 'Reschedule proposed'), ('customer_accepted_reschedule', 'Customer accepted reschedule'), ('customer_declined_reschedule', 'Customer declined reschedule'), ('scheduling_failed', 'Scheduling failed'), ('fee_resolution_chosen', 'Fee resolution chosen'), ('partner_en_route', 'Partner en route'), ('partner_arrived', 'Partner arrived'), ('viewing_started', 'Viewing started'), ('viewing_completed', 'Viewing completed'), ('customer_no_show', 'Customer did not attend'), ('partner_no_show', 'Partner did not attend'), ('viewing_cancelled', 'Viewing cancelled'), ('refund_issued', 'Refund issued'), ('dispute_opened', 'Dispute opened')], db_index=True, max_length=40),
        ),
    ]
