# Generated by Django 6.0.6 on 2026-07-26 22:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_partner_commission_plan_and_more'),
        ('properties', '0003_alter_property_partner'),
        ('viewings', '0008_alter_viewing_fee_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('commission_pending', 'Commission Pending'), ('commission_paid', 'Commission Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_confirmation', max_length=40)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('partner_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='partners.partner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='properties.property')),
                ('viewing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='viewings.viewing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
