# Generated by Django 6.0.6 on 2026-07-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner')], max_length=20)),
                ('outcome', models.CharField(choices=[('rented', 'Customer rented property'), ('purchased', 'Customer bought property'), ('still_deciding', 'Still deciding'), ('declined', 'Declined property'), ('no_show', 'Did not attend')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='deals.deal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deal', 'reporter'), name='one_outcome_per_reporter')],
            },
        ),
    ]
