# Generated by Django 6.0.6 on 2026-08-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_commissioninvoice'),
        ('introductions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('sale', 'Sale')], max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='introduction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='introductions.protectedintroduction'),
        ),
        migrations.AddField(
            model_name='deal',
            name='owner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='owner_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='partner_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_customer', 'Awaiting customer confirmation'), ('awaiting_owner', 'Awaiting owner confirmation'), ('negotiating', 'Negotiating'), ('agreed', 'Terms agreed'), ('documents_pending', 'Documents pending'), ('commission_due', 'Commission due'), ('commission_paid', 'Commission paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=40),
        ),
        migrations.CreateModel(
            name='DealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_events', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='deals.deal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
