# Generated by Django 6.0.6 on 2026-08-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_agreed_at_deal_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealevent',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_partner', 'Awaiting partner confirmation'), ('awaiting_confirmations', 'Awaiting confirmations'), ('negotiating', 'Negotiating'), ('agreed', 'All parties confirmed'), ('documents_pending', 'Documents pending'), ('commission_due', 'Commission due'), ('commission_paid', 'Commission paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=40),
        ),
    ]
