# Generated by Django 6.0.6 on 2026-08-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_dealevent_options_alter_deal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealoutcome',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='dealoutcome',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='dealoutcome',
            name='reporter',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('owner', 'Owner')], max_length=20),
        ),
    ]
