# Generated by Django 6.0.6 on 2026-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_dealoutcome_options_alter_dealoutcome_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_partner', 'Awaiting partner confirmation'), ('awaiting_confirmations', 'Awaiting customer, partner, and owner confirmations'), ('negotiating', 'Negotiating'), ('agreed', 'All parties confirmed'), ('documents_pending', 'Documents pending'), ('commission_due', 'Commission due'), ('commission_paid', 'Commission paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=40),
        ),
    ]
