# Generated by Django 6.0.6 on 2026-08-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_deal_status'),
        ('mandates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_owner_confirmation_tokens', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_confirmation_tokens', to='deals.deal')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_confirmation_tokens', to='mandates.propertymandate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_confirmation_tokens', to='mandates.propertyowner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', 'expires_at'], name='deals_owner_deal_id_3b8ba9_idx')],
            },
        ),
    ]
