# Generated by Django 6.0.6 on 2026-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_ownerconfirmationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_customer', 'Awaiting customer confirmation'), ('awaiting_owner', 'Awaiting owner confirmation'), ('awaiting_confirmations', 'Awaiting customer, partner, and owner confirmations'), ('negotiating', 'Negotiating'), ('agreed', 'Terms agreed'), ('documents_pending', 'Documents pending'), ('commission_due', 'Commission due'), ('commission_paid', 'Commission paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=40),
        ),
    ]
