# Generated by Django 6.0.6 on 2026-08-25 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_commissionsettlementpayment'),
        ('deals', '0009_alter_deal_status'),
        ('mandates', '0003_remove_propertymandate_owner_signed_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissioninvoice',
            options={'ordering': ['-issued_at', '-id']},
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoices', to='commissions.commissionagreement'),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='agreement_number_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoices', to='mandates.propertyowner'),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='owner_email_snapshot',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='owner_legal_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='owner_number_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='owner_phone_number_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='settlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoice', to='commissions.commissionsettlement'),
        ),
        migrations.AddField(
            model_name='commissioninvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commissioninvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commissioninvoice',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoice', to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='commissioninvoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='commissioninvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
