# Generated by Django 6.0.6 on 2026-08-25 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alter_commissioninvoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=30)),
                ('payment_reference', models.CharField(db_index=True, max_length=150)),
                ('received_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='deals.commissioninvoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_commission_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invoice', 'received_at', 'id'],
            },
        ),
    ]
