# Generated by Django 6.0.6 on 2026-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_commissionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
