# Generated by Django 6.0.6 on 2026-07-24 22:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_alter_property_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('partner_share_rate', models.DecimalField(decimal_places=2, help_text='Partner earning percentage, such as 20.00.', max_digits=5)),
                ('minimum_completed_transactions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['minimum_completed_transactions', 'partner_share_rate'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone_number', models.CharField(max_length=30)),
                ('commission_method', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=3, help_text='For example, enter 3.000 for a 3% commission.', max_digits=6, null=True)),
                ('fixed_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transaction_value', models.DecimalField(decimal_places=2, help_text='The expected rent or sale value used to calculate commission.', max_digits=14)),
                ('expected_total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_owner_confirmation', 'Awaiting owner confirmation'), ('owner_confirmed', 'Owner confirmed'), ('verified', 'Verified'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_agreements', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_agreement', to='properties.property')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_commission_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
