# Generated by Django 6.0.6 on 2026-07-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionplan',
            options={'ordering': ['partner_share_rate', 'name']},
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='agreement_number',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='For percentage agreements, enter the agreed rate. For example, enter 3.000 for 3%.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='fixed_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed commission amount. Required only for fixed agreements.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, help_text='The expected rent or sale value used to calculate the commission.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='commissionplan',
            name='minimum_completed_transactions',
            field=models.PositiveIntegerField(default=0, help_text='The minimum number of completed transactions normally required for this level.'),
        ),
        migrations.AlterField(
            model_name='commissionplan',
            name='partner_share_rate',
            field=models.DecimalField(decimal_places=2, help_text="The partner's earning percentage. For example, enter 20.00 for Bronze.", max_digits=5),
        ),
    ]
