# Generated by Django 6.0.6 on 2026-07-27 00:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commissionplan_options_and_more'),
        ('deals', '0003_commissioninvoice'),
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_commission_amount', models.DecimalField(decimal_places=2, help_text='The complete commission available for allocation. This is normally copied from the locked commission agreement.', max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('allocation_pending', 'Allocation pending'), ('allocated', 'Allocated'), ('approved', 'Approved'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='commissions.commissionagreement')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commission_settlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_settlements', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlement', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlementParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('pata_hao', 'Pata Hao'), ('listing_partner', 'Listing partner'), ('customer_agent', 'Customer agent'), ('seller_agent', 'Seller agent'), ('referral_agent', 'Referral agent'), ('property_owner', 'Property owner'), ('other', 'Other')], max_length=30)),
                ('participant_name', models.CharField(blank=True, help_text='Use this for an external agent or participant who does not have a Pata Hao partner account.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentage_of_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=7)),
                ('is_platform_share', models.BooleanField(default=False, help_text='Select this when the allocation belongs to Pata Hao.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlement_shares', to='partners.partner')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='commissions.commissionsettlement')),
            ],
            options={
                'ordering': ['settlement', 'participant_type', 'participant_name'],
            },
        ),
    ]
