# Generated by Django 6.0.6 on 2026-08-13 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commissionsettlement_commissionsettlementparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionagreement',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_commission_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionagreement',
            name='commission_basis',
            field=models.CharField(choices=[('first_month_rent', "First month's rent"), ('sale_price', 'Sale price'), ('transaction_value', 'Agreed transaction value')], default='first_month_rent', max_length=30),
        ),
        migrations.AddField(
            model_name='commissionagreement',
            name='partner_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionagreement',
            name='partner_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
