# Generated by Django 6.0.6 on 2026-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionagreement_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionagreement',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='For percentage agreements, enter the agreed rate. For example, enter 10.000 for 10%.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('locked', 'Locked'), ('cancelled', 'Cancelled'), ('awaiting_owner_confirmation', 'Awaiting owner confirmation'), ('owner_confirmed', 'Owner confirmed')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='commissionagreement',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, help_text='The rent, sale price, or agreed transaction value used to calculate the commission.', max_digits=14),
        ),
    ]
