# Generated by Django 6.0.6 on 2026-09-16 12:18

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def validate_existing_payout_references(apps, schema_editor):
    payment_model = apps.get_model(
        'commissions',
        'CommissionSettlementPayment',
    )
    duplicates = list(
        payment_model.objects
        .annotate(
            normalized_reference=(
                django.db.models.functions.text.Lower(
                    'payment_reference'
                )
            )
        )
        .values('normalized_reference')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('normalized_reference', flat=True)[:5]
    )

    if duplicates:
        raise RuntimeError(
            'Resolve duplicate commission payout references before '
            'applying commissions.0007: '
            + ', '.join(duplicates)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_commissionsettlementpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_existing_payout_references,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='commissionsettlementpayment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('payment_reference'), name='comm_payout_ref_ci_uniq'),
        ),
    ]
