# Generated by Django 6.0.6 on 2026-08-01 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_partner_commission_plan_and_more'),
        ('properties', '0008_favorite'),
        ('viewings', '0009_viewingfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('completed_viewings', models.PositiveIntegerField(default=0)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_viewings', models.PositiveIntegerField(default=0)),
                ('missed_viewings', models.PositiveIntegerField(default=0)),
                ('cancelled_viewings', models.PositiveIntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('completed_viewings', models.PositiveIntegerField(default=0)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('accepted_viewings', models.PositiveIntegerField(default=0)),
                ('declined_viewings', models.PositiveIntegerField(default=0)),
                ('rescheduled_viewings', models.PositiveIntegerField(default=0)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_record', to='partners.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('completed_viewings', models.PositiveIntegerField(default=0)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('accurate_feedback_count', models.PositiveIntegerField(default=0)),
                ('partially_accurate_feedback_count', models.PositiveIntegerField(default=0)),
                ('inaccurate_feedback_count', models.PositiveIntegerField(default=0)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_record', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('property', 'Property')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('previous_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_changes', to='viewings.viewing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='trust_trust_subject_bbe859_idx')],
            },
        ),
    ]
