# Generated by Django 6.0.6 on 2026-08-06 23:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertrustscore',
            name='active_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='calculation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='confirmed_violations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='dispute_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='disputed_deals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='evaluated_deals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='grade',
            field=models.CharField(choices=[('unrated', 'Unrated'), ('high_risk', 'High risk'), ('developing', 'Developing'), ('good', 'Good'), ('trusted', 'Trusted'), ('excellent', 'Excellent')], default='unrated', max_length=20),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='owner_confirmation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='permanently_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='successful_deals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnertrustscore',
            name='viewing_completion_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
