# Generated by Django 6.0.6 on 2026-07-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_and_more'),
        ('properties', '0002_propertyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='partners.partner'),
        ),
    ]
