# Generated by Django 6.0.6 on 2026-08-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_commission_plan_and_more'),
        ('properties', '0003_alter_property_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('source', 'Source partner'), ('participating', 'Participating partner')], default='participating', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_participations', to='partners.partner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_participations', to='properties.property')),
            ],
            options={
                'ordering': ['property_id', 'partner_id'],
                'constraints': [models.UniqueConstraint(fields=('property', 'partner'), name='unique_partner_per_property')],
            },
        ),
    ]
