# Generated by Django 6.0.6 on 2026-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='verification_return_reason',
            field=models.TextField(blank=True, help_text='Reason a pending property was returned to the partner for changes.'),
        ),
    ]
