# Generated by Django 6.0.6 on 2026-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_verification_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='success_broadcast_until',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
