# Generated by Django 6.0.6 on 2026-09-17 10:50

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


def preserve_existing_videos(apps, schema_editor):
    PropertyVideo = apps.get_model("properties", "PropertyVideo")
    database_alias = schema_editor.connection.alias
    videos = PropertyVideo.objects.using(database_alias)

    videos.update(review_status="approved")

    property_ids = (
        videos.filter(is_featured=True)
        .order_by()
        .values_list("property_id", flat=True)
        .distinct()
    )

    for property_id in property_ids:
        featured_ids = list(
            videos.filter(
                property_id=property_id,
                is_featured=True,
            )
            .order_by("-uploaded_at", "-id")
            .values_list("id", flat=True)
        )

        videos.filter(id__in=featured_ids[1:]).update(
            is_featured=False,
        )


def restore_pending_status(apps, schema_editor):
    PropertyVideo = apps.get_model("properties", "PropertyVideo")
    PropertyVideo.objects.using(
        schema_editor.connection.alias,
    ).update(review_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyamenity_property_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='audio_codec',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='content_sha256',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='file_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Returned for replacement')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_property_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_property_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='video_codec',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_video_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to=properties.models.property_video_upload_path),
        ),
        migrations.RunPython(
            preserve_existing_videos,
            reverse_code=restore_pending_status,
        ),
        migrations.AddConstraint(
            model_name='propertyvideo',
            constraint=models.UniqueConstraint(condition=models.Q(('content_sha256__gt', '')), fields=('property', 'content_sha256'), name='unique_property_video_content'),
        ),
        migrations.AddConstraint(
            model_name='propertyvideo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('property',), name='unique_featured_video_per_property'),
        ),
    ]
