# Generated by Django 6.0.6 on 2026-08-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('property_limit', models.PositiveIntegerField()),
                ('minimum_completed_deals', models.PositiveIntegerField(default=0)),
                ('minimum_trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPromotionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_deals', models.PositiveIntegerField()),
                ('violations', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner')),
                ('current_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.partnertier')),
                ('proposed_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.partnertier')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_tier_assignments', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_history', to='partners.partner')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='governance.partnertier')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
