# Generated by Django 6.0.6 on 2026-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpromotionreview',
            name='metrics_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
