# Generated by Django 6.0.6 on 2026-08-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_partnerpromotionreview_metrics_snapshot'),
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('gross_misconduct', 'Gross misconduct')], max_length=30)),
                ('recommended_action', models.CharField(choices=[('warning', 'Warning'), ('short_suspension', 'Short suspension'), ('long_suspension', 'Long suspension'), ('permanent_ban', 'Permanent ban')], max_length=30)),
                ('effective_from', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PartnerViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('awaiting_response', 'Awaiting partner response'), ('dismissed', 'Dismissed'), ('confirmed', 'Confirmed')], default='reported', max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_violations', to='partners.partner')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_partner_violations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_partner_violations', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='governance.policyrule')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
                'indexes': [models.Index(fields=['partner', 'status'], name='governance__partner_2ea3b8_idx'), models.Index(fields=['policy', 'status'], name='governance__policy__8cc861_idx')],
            },
        ),
    ]
