# Generated by Django 6.0.6 on 2026-08-06 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_policyrule_partnerviolation'),
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Formal warning'), ('short_suspension', 'Short suspension'), ('long_suspension', 'Long suspension'), ('permanent_ban', 'Permanent ban')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('reason', models.TextField()),
                ('decision_snapshot', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('imposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imposed_partner_disciplinary_actions', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_actions', to='partners.partner')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_partner_disciplinary_actions', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_actions', to='governance.partnerviolation')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
                'indexes': [models.Index(fields=['partner', 'status'], name='governance__partner_68d112_idx'), models.Index(fields=['action_type', 'status'], name='governance__action__e5206c_idx')],
            },
        ),
    ]
