# Generated by Django 6.0.6 on 2026-08-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_partnerdisciplinaryaction'),
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReinstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('reinstated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_partner_reinstatements', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinstatements', to='partners.partner')),
                ('reviewed_actions', models.ManyToManyField(blank=True, related_name='reinstatements', to='governance.partnerdisciplinaryaction')),
            ],
            options={
                'ordering': ['-reinstated_at', '-id'],
            },
        ),
    ]
