# Generated by Django 6.0.6 on 2026-08-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_deal_status'),
        ('governance', '0005_partnerreinstatement'),
        ('partners', '0003_partner_commission_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealGovernanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('responsible_role', models.CharField(choices=[('partner', 'Partner'), ('staff', 'Pata Hao staff'), ('owner', 'Property owner'), ('customer', 'Customer')], db_index=True, max_length=20)),
                ('action_code', models.CharField(max_length=80)),
                ('action_label', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_deal_governance_cases', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_cases', to='deals.deal')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_governance_cases', to='partners.partner')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_deal_governance_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'responsible_role', '-created_at'], name='governance__status_32769b_idx'), models.Index(fields=['deal', 'status'], name='governance__deal_id_551545_idx'), models.Index(fields=['partner', 'status'], name='governance__partner_bb3159_idx')],
            },
        ),
    ]
