# Generated by Django 6.0.6 on 2026-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_dealgovernancecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertier',
            name='commission_share_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of an eligible Pata Hao commission allocated to a partner in this tier.', max_digits=5, null=True),
        ),
    ]
