# Generated by Django 6.0.6 on 2026-07-19 00:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_payment_viewing_and_more'),
        ('viewings', '0006_viewingevent_alter_viewingbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_callback_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile money'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money')], default='mpesa', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(default='viewing_fee', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='viewing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='viewings.viewing'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'status', '-created_at'], name='payment_payer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status', '-created_at'], name='payment_provider_status_idx'),
        ),
    ]
