# Generated by Django 6.0.6 on 2026-07-25 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_callback_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), editable=False, max_digits=10),
        ),
    ]
