# Generated by Django 6.0.6 on 2026-09-11 15:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_amount'),
        ('viewings', '0012_viewing_fee_resolution_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_notes',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reference',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_viewing_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ViewingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_reference', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('void', 'Void')], db_index=True, default='active', editable=False, max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_credits', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_viewing_credits', to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_credit', to='payments.payment')),
                ('source_viewing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credit', to='viewings.viewing')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='viewcredit_amount_positive'), models.CheckConstraint(condition=models.Q(('remaining_amount__gte', Decimal('0.00')), ('remaining_amount__lte', models.F('amount'))), name='viewcredit_remaining_valid')],
            },
        ),
    ]
