# Generated by Django 6.0.6 on 2026-09-16 12:18

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def validate_existing_payment_identifiers(apps, schema_editor):
    payment_model = apps.get_model('payments', 'Payment')

    duplicate_references = list(
        payment_model.objects
        .exclude(payment_reference='')
        .values('payment_reference')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('payment_reference', flat=True)[:5]
    )
    duplicate_checkouts = list(
        payment_model.objects
        .exclude(checkout_request_id='')
        .values('checkout_request_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('checkout_request_id', flat=True)[:5]
    )
    duplicate_receipts = list(
        payment_model.objects
        .exclude(provider_receipt_number='')
        .annotate(
            normalized_receipt=(
                django.db.models.functions.text.Lower(
                    'provider_receipt_number'
                )
            )
        )
        .values('normalized_receipt')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('normalized_receipt', flat=True)[:5]
    )

    conflicts = {
        'payment references': duplicate_references,
        'checkout request identifiers': duplicate_checkouts,
        'provider receipt numbers': duplicate_receipts,
    }
    conflicts = {
        label: values
        for label, values in conflicts.items()
        if values
    }

    if conflicts:
        details = '; '.join(
            f"{label}: {', '.join(values)}"
            for label, values in conflicts.items()
        )
        raise RuntimeError(
            'Resolve duplicate payment evidence before applying '
            f'payments.0008 ({details}).'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_refund_notes_payment_refund_reference_and_more'),
        ('viewings', '0012_viewing_fee_resolution_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_existing_payment_identifiers,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_reference', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('review_required', 'Review required')], db_index=True, default='processing', editable=False, max_length=30)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=150)),
                ('provider_receipt_number', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=120)),
                ('requested_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('callback_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('provider_response_code', models.CharField(blank=True, default='', editable=False, max_length=50)),
                ('provider_response_description', models.TextField(blank=True, default='', editable=False)),
                ('failure_reason', models.TextField(blank=True, default='', editable=False)),
                ('provider_request_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('provider_response_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('provider_callback_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('provider_query_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('callback_received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('payment_reference',), name='payment_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('provider_receipt_number'), condition=models.Q(('provider_receipt_number', ''), _negated=True), name='pay_provider_receipt_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id', ''), _negated=True), fields=('checkout_request_id',), name='pay_checkout_request_uniq'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'status', '-created_at'], name='payattempt_payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id', ''), _negated=True), fields=('checkout_request_id',), name='payattempt_checkout_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('provider_receipt_number'), condition=models.Q(('provider_receipt_number', ''), _negated=True), name='payattempt_receipt_ci_uniq'),
        ),
    ]
