# Generated by Django 6.0.6 on 2026-09-25 18:51

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_existing_cash_amounts(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    Payment.objects.update(cash_amount=models.F("amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentattempt_payment_payment_reference_unique_and_more'),
        ('viewings', '0013_repair_paid_partner_declines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingCreditRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('redemption_reference', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile money'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('viewing_credit', 'Pata Hao viewing credit')], default='mpesa', max_length=30),
        ),
        migrations.RunPython(
            backfill_existing_cash_amounts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('credit_applied_amount__gte', Decimal('0.00'))), name='pay_credit_applied_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', Decimal('0.00'))), name='pay_cash_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('credit_applied_amount'), '+', models.F('cash_amount')))), name='pay_amount_breakdown_matches'),
        ),
        migrations.AddField(
            model_name='viewingcreditredemption',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='payments.viewingcredit'),
        ),
        migrations.AddField(
            model_name='viewingcreditredemption',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_redemptions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='viewingcreditredemption',
            name='viewing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_redemptions', to='viewings.viewing'),
        ),
        migrations.AddConstraint(
            model_name='viewingcreditredemption',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='viewcredit_redemption_positive'),
        ),
        migrations.AddConstraint(
            model_name='viewingcreditredemption',
            constraint=models.UniqueConstraint(fields=('credit', 'payment'), name='viewcredit_once_per_payment'),
        ),
    ]
