# Generated by Django 6.0.6 on 2026-08-03 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0003_commissionsettlement_commissionsettlementparticipant'),
        ('mandates', '0001_initial'),
        ('partners', '0003_partner_commission_plan_and_more'),
        ('properties', '0003_alter_property_partner'),
        ('viewings', '0009_viewingfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted_to_deal', 'Converted to deal'), ('expired', 'Expired'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=30)),
                ('protected_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('protected_until', models.DateTimeField()),
                ('protection_period_days', models.PositiveIntegerField()),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('property_title_snapshot', models.CharField(max_length=255)),
                ('listing_type_snapshot', models.CharField(max_length=30)),
                ('property_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('owner_name_snapshot', models.CharField(max_length=255)),
                ('partner_name_snapshot', models.CharField(max_length=255)),
                ('mandate_number_snapshot', models.CharField(max_length=50)),
                ('commission_agreement_number_snapshot', models.CharField(max_length=50)),
                ('commission_method_snapshot', models.CharField(max_length=20)),
                ('commission_rate_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fixed_commission_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_commission_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_snapshot', models.CharField(default='KES', max_length=3)),
                ('viewing_fee_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('viewing_payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificates', to='commissions.commissionagreement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificates', to=settings.AUTH_USER_MODEL)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificates', to='mandates.propertymandate')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificates', to='partners.partner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificates', to='properties.property')),
                ('viewing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='property_introduction_certificate', to='viewings.viewing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntroductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_introduction_events', to=settings.AUTH_USER_MODEL)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='introductions.protectedintroduction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='protectedintroduction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'converted_to_deal', 'disputed'])), fields=('customer', 'property'), name='one_active_pic_per_customer_property'),
        ),
    ]
