# Generated by Django 6.0.6 on 2026-07-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['business_name']},
        ),
        migrations.AddField(
            model_name='partner',
            name='accepts_viewing_requests',
            field=models.BooleanField(default=True, help_text='Controls whether customers can request viewings.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bio',
            field=models.TextField(blank=True, help_text='Short public description shown on the partner profile.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public name shown to customers.', max_length=150),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='Private verification information. Never expose publicly.', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_code',
            field=models.CharField(blank=True, help_text='Unique public Pata Hao partner reference.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_profiles/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='public_phone_number',
            field=models.CharField(blank=True, help_text='Optional number that may be shown after booking confirmation.', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='service_area',
            field=models.CharField(blank=True, help_text='Estate, neighborhood, town, or territory served.', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Private admin verification notes.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=30),
        ),
    ]
