# Generated by Django 6.0.6 on 2026-07-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('partners', '0002_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='commission_plan',
            field=models.ForeignKey(blank=True, help_text="The partner's current Pata Hao earning level.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='commissions.commissionplan'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Legacy commission percentage.', max_digits=5),
        ),
    ]
