# Generated by Django 6.0.6 on 2026-08-02 23:21

import django.db.models.deletion
import mandates.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0003_commissionsettlement_commissionsettlementparticipant'),
        ('partners', '0003_partner_commission_plan_and_more'),
        ('properties', '0003_alter_property_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_number', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_signature', 'Awaiting owner signature'), ('signed_uploaded', 'Signed document uploaded'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('protection_period_days', models.PositiveIntegerField(default=180)),
                ('owner_signed_date', models.DateField(blank=True, null=True)),
                ('no_cash_acknowledged', models.BooleanField(default=False, help_text='Owner acknowledged that cash and direct off-platform payments are prohibited.')),
                ('anti_circumvention_acknowledged', models.BooleanField(default=False, help_text='Owner acknowledged that Pata Hao introductions cannot be bypassed.')),
                ('owner_authority_confirmed', models.BooleanField(default=False, help_text='Owner or authorized representative confirmed authority to mandate this property.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_property_mandates', to=settings.AUTH_USER_MODEL)),
                ('commission_agreement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='property_mandate', to='commissions.commissionagreement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_property_mandates', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_mandates', to='partners.partner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MandateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandate_events', to=settings.AUTH_USER_MODEL)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mandates.propertymandate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('trust', 'Trust or estate'), ('other', 'Other')], default='individual', max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id_number', models.CharField(blank=True, help_text='Private. Never expose through public APIs.', max_length=80)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('kra_pin', models.CharField(blank=True, max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_property_owners', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_property_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='mandates.propertyowner'),
        ),
        migrations.CreateModel(
            name='MandateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('signed_mandate', 'Signed property mandate'), ('owner_id', 'Owner identification'), ('ownership_proof', 'Ownership proof'), ('authority_letter', 'Authority letter'), ('company_resolution', 'Company resolution'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=mandates.models.mandate_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='uploaded', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mandate_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_mandate_documents', to=settings.AUTH_USER_MODEL)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='mandates.propertymandate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('mandate', 'document_type'), name='one_current_document_per_mandate_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='propertymandate',
            constraint=models.UniqueConstraint(fields=('property', 'version'), name='unique_mandate_version_per_property'),
        ),
    ]
