# Generated by Django 6.0.6 on 2026-08-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commissionsettlement_commissionsettlementparticipant'),
        ('mandates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymandate',
            name='commission_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_mandate', to='commissions.commissionagreement'),
        ),
    ]
