# Generated by Django 6.0.6 on 2026-08-13 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandates', '0002_alter_propertymandate_commission_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymandate',
            name='owner_signed_date',
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='authorization_method',
            field=models.CharField(choices=[('verbal', 'Verbal authorization'), ('phone', 'Phone authorization'), ('whatsapp', 'WhatsApp or message authorization'), ('written', 'Written authorization'), ('property_manager', 'Property management authority'), ('owner_self', 'Partner is the owner'), ('other', 'Other')], default='verbal', max_length=30),
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='authorization_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='declaration_version',
            field=models.CharField(default='2026.1', max_length=30),
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declared_property_mandates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='partner_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymandate',
            name='partner_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymandate',
            name='anti_circumvention_acknowledged',
            field=models.BooleanField(default=False, help_text='Partner acknowledged that Pata Hao introductions cannot knowingly be bypassed to avoid agreed commissions.'),
        ),
        migrations.AlterField(
            model_name='propertymandate',
            name='no_cash_acknowledged',
            field=models.BooleanField(default=False, help_text='Partner acknowledged Pata Hao platform payments and recorded transaction flows must not be bypassed.'),
        ),
        migrations.AlterField(
            model_name='propertymandate',
            name='owner_authority_confirmed',
            field=models.BooleanField(default=False, help_text='Partner declares that the owner/landlord/authorized representative gave authority to market this property.'),
        ),
        migrations.AlterField(
            model_name='propertymandate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_partner_acceptance', 'Awaiting partner acceptance'), ('partner_accepted', 'Partner accepted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=40),
        ),
    ]
