# Generated by Django 6.0.6 on 2026-09-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandates', '0004_protect_mandate_event_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationReview',
            fields=[
            ],
            options={
                'verbose_name': 'Authorization review',
                'verbose_name_plural': 'Authorization reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mandates.propertymandate',),
        ),
    ]
